### PR TITLE
Bring add-bbmap branch up to speed with recent MultiQC developments

### PR DESCRIPTION
**Pull request by boulund**
Merged the add-bbmap branch with recent MultiQC master branch.
Made some more minor adjustments to bbmap module code to work with new MultiQC features.

This is the status of all BBMap file types currently in the module code, as far as I can tell:

'Finished' | File type | Implemented | Description | Comment
-- | -- | -- | -- | --
No  | aqhist | Yes | Histogram   of average read quality | Plot incomplete: not all data is plotted
-  | basecov | No | Coverage   per base location | Too big   to do something useful with
No  | bhist | Yes | Base composition histogram by pos | Plot error: Only plots a single point for each sample: 0
No   | bqhist | Yes | Base quality histogram designed for boxplot | Plot error: Only plots count_1 for all basenum positions.
Yes  | covhist | Yes | Histogram   of # occurences of each depth level | Looks all right, now with logarithmic y-axis
-  | covstats | No | Per-scaffold   coverage info | Too   complex info to summarize/visualize in a useful way in MultiQC?
Yes   | ehist | Yes | Errors-per-read   histogram | Looks   all right
Yes   | gchist | Yes | Read GC   content histogram | Looks   all right
Yes   | idhist | Yes | Histogram   of read count versus percent identity | Looks   all right
Yes   | ihist | Yes | Histogram   of insert sizes (for paired reads) | Looks   all right
Yes   | indelhist | Yes | Indel   length histogram | Looks   all right
Yes   | lhist | Yes | Read   length histogram | Looks   all right, now with logarithmic y-axis
No  | mhist | Yes? | Histogram   of match, sub, del, and ins rates by read location | Plot   error: only plots a single points for each sample: 1
Yes   | qahist | Yes | Quality   accuracy historgram of error rates vs quality score | Looks   all right
No  | qhist | Yes | Quality   histogram by position | Plot   error: looks like some data is not plotted
No | rpkm | No | Per-scaffold   RPKM/FPKM counts | Complex   data, might be hard to plot in a useful way

I think the most important ones to take care of going forward are `aqhist`, `bhist`, `bqhist`, `mhist`, `qhist`, and perhaps `rpkm` (if it's even possible to summarize in a useful way). The code currently doesn't handle data from log files containing multiple columns that should be plotted against the same x-axis properly. This is probably an easy thing to fix, but I haven't had time to look into it yet.

### CODE REVIEW

**Comment by boulund** [comment]
It might be a good idea to rebase or squash most of these commits now that I see the massive amount of commits I accidentally included in this PR... Sorry for that. I'm a bit of a git noob :)

**Comment by boulund** [comment]
I had a quick chat with @ewels on whether it's possible somehow to plot e.g. the `aqhist` data as two lines per sample in the plot, but that's probably not a good solution. We'll have to see if we can figure out some good ways to summarize the information contained in the more complex log outputs somehow.

**Comment by boulund** [comment]
I updated the first comment slightly as I noticed I left out `bqhist` from the list. `bqhist` suffers from the same issue as other plots with multiple columns. Seeing as `bqhist` really is just a `qhist` with additional information (i.e. the data required for a full boxplot in each position) we could probably skip `bqhist` for the time being by setting it as `not_implemented`.

**Comment by ewels** [comment]
Re: `aqhist`: _Histogram of average read quality._ - how is this different to the [FastQC _Per Sequence Quality Scores_ plot](http://multiqc.info/examples/rna-seq/multiqc_report.html#fastqc_per_sequence_quality_scores)? That's essentially a histogram of average read quality..

**Comment by boulund** [comment]
@ewels You're entirely correct in that it is the same thing, just that it's output from BBMap/BBDuk. 
For me, in my workflows, I find the benefit of having the output from BBMap is that I don't have to spend time running FastQC (as it's so slow) since BBMap outputs the data without having to going through the fastq files twice. 
Edit: Since FastQC only runs on a single fastq file, the same issue doesn't occur; BBMap runs on the fastq pair and produces both average quality histograms in the same file. Of course, they could be split into two separate "samples" (e.g. "sample1-read1", "sample1-read2") and plotted separately, but that would lead to tons of lines like we discussed yesterday.

**Comment by boulund** [comment]
I'm getting more and more keen on refactoring @epruesse's plotting code a bit, or at least break out code for all the plots that require further customizations into their own submodule, as it is bound to get too messy to handle everything in the same plotting function eventually. 
I'm leaving for vacation now, so I won't be doing any more work on this until I get back in the middle of August, at the earliest.

**Comment by ewels** [comment]
@boulund - I understand why it's useful to have in the report, I more meant as a model of how it could be plotted sorry. Having two reads is no problem for scaling, you can just have [two tabbed plots](http://multiqc.info/docs/#switching-datasets-1), one for R1 and one for R2. This is actually much nicer than FastQC, where we are essentially forced to plot both reads as it doesn't handle paired-end datasets. It's when you have loads of lines per sample that the scaling goes badly, two isn't so bad (apologies if I misunderstood you in our slack conversation).

Personally I think having separate scripts for the separate output types (even if from the same tool) makes maintenance and debugging much easier, even if the code is more verbose and duplicative. The main script can still hold common functions.

**Comment by boulund** [comment]
@ewels Yes, sorry! I agree that it's a useful model of how to potentially plot this data. Having R1 and R2 in separate tabs of the plot is a good idea, I think we'll do that. 

Totally agree with you on putting the plotting code for all the separate output types in submodules, at least the ones that are not just simple histograms.

**Comment by epruesse** [comment]
Oh my, that's a lot of commits. I thought I'd given you write access to this fork. Should I merge or rebase? I haven't had this situation before, not sure how to get back to a clean history.

**Comment by epruesse** [comment]
Ah, yes , you should have full access. So you could do `rebase`/`push -f`.

**Comment by ewels** [comment]
Sorry, are you talking to me or @boulund?

**Comment by boulund** [comment]
Yes, sorry for the mess.

I'm not as used to git/github as with mercurial, but learning as I go
along! I'll rebase as soon as I finish adding separate plotting functions
for the file types that require it. Have a nice weekend!

Den 18 aug. 2017 16:16 skrev "Elmar Pruesse" <notifications@github.com>:

**Comment by epruesse** [comment]
I meant Frederik @boulund.

**Comment by epruesse** [comment]
No worries. Sorry I haven't been able to work on this in the last few months. :/

**Comment by boulund** [comment]
Ok, so I've been reading up on how to best solve this mess that I've created. 
Intuitively, I feel like I should be able to rebase the entire messy `add-bbmap` branch on top of the most recent commit of `ewels/master`, but unfortunately I've no real idea of how to do that properly. I've played with some copies of my local repo to try to `rebase` or `cherry-pick` my way out of this, but none seemed to work very well. In fact, it all seemed to become even messier. If you have experience of similar situation from before, please share :). 

I have another solution that might work, if you're ok with losing some commit history of how all bbmap-related files were created. It doesn't feel like the perfect solution, but at least it should be very clean:

1. In a local copy of my repo, I reset the `master` branch to the state of `epruesse`'s repo when I started.
2. Then I pulled all commits to master from `ewels/master` in one merge commit on top of that. That puts us in sync with `ewels/master`. 
3. (Here, I could update `epruesse/master` to sync it to `ewels/master`, by making a PR from `boulund/master` to bring `epruesse/master` in sync. )
4. Then, I branched off a new `bbmap` branch from my local `master`, and in a single commit performed a checkout of all the files from the `add-bbmap` branch that were relevant to the module, thus making all of the development that has happened in the `add-bbmap` branch included as a single commit in the `bbmap` branch. 

This has the unfortunate downside that this squashes the entire history of everything in the `add-bbmap` branch into a single commit on the new `bbmap` branch. However, on the plus side, it will be very neat with only a single commit :).
Do you have any better ideas or tips on how I could approach this mess? I've practically no experience solving issues like this with git, unfortunately.

**Comment by boulund** [comment]
I went forward and created a new branch `bbmap` that includes a manually squashed commit of all bbmap module files. Work will continue in that branch instead, as it has a much cleaner history.

**Comment by epruesse** [comment]
@boulund Sorry, I just didn't find the time :(

**Comment by boulund** [comment]
Absolutely no problem @epruesse ! There's still work to be done on the module, so if/when you have the time, there's a lot of possibilities to have another look at what we made :)

**Pull request closed without merging**
